name: Crash Report
description: File a crash report
labels: ["crash"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the crash
      description: A clear and concise description of what the crash is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the crash
      description: Please describe how to reproduce the crash, if you provide a minimal reproduction, explain how to get the crash to appear from there.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: In order for us to solve the issue, you must provide a crashlog and SBLT log. You can find the SBLT log in mods/logs and crashlog in %localappdata%/payday 2/crash.txt
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: To allow maintainers to focus on the issue better and to try resolving it, it is highly recommended to include a minimal project with said issue.
